require: rubocop-rspec


Metrics/LineLength:
  Max: 120
AllCops:
  Excludes:
    - db/**/**
    - config/**/**
    - bin/**/**
    - spec/*.rb
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  Rails:
    Enabled: true
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact
