require: rubocop-rspec


Metrics/LineLength:
  Max: 120
AllCops:
  Excludes:
    - db/**/**
    - config/**/**
    - bin/**/**
    - spec/*.rb
  Rails:
    Enabled: true
Documentation:
  Enabled: false